// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class CFileChat;
@class CFileChat_Builder;
@class CLineChat;
@class CLineChat_Builder;
@class CListChat;
@class CListChat_Builder;
@class CPrivateChat;
@class CPrivateChat_Builder;
typedef enum {
  ContentTypeContent = 1,
  ContentTypePhoto = 2,
  ContentTypeAudio = 3,
  ContentTypeFile = 4,
  ContentTypeVideo = 5,
} ContentType;

BOOL ContentTypeIsValidValue(ContentType value);

typedef enum {
  StateTypeOnLine = 1,
  StateTypeOutLine = 2,
} StateType;

BOOL StateTypeIsValidValue(StateType value);

typedef enum {
  ChatTypeGroup = 1,
  ChatTypePoint = 2,
} ChatType;

BOOL ChatTypeIsValidValue(ChatType value);


@interface ChatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CPrivateChat : PBGeneratedMessage {
@private
  BOOL hasSelf_:1;
  BOOL hasDest_:1;
  BOOL hasContentTime_:1;
  BOOL hasContent_:1;
  BOOL hasInitialFileName_:1;
  BOOL hasNewFileName_:1;
  BOOL hasGroupId_:1;
  BOOL hasFile_:1;
  BOOL hasContentType_:1;
  BOOL hasChatType_:1;
  NSString* self;
  NSString* dest;
  NSString* contentTime;
  NSString* content;
  NSString* initialFileName;
  NSString* newFileName;
  NSString* groupId;
  NSData* file;
  ContentType contentType;
  ChatType chatType;
}
- (BOOL) hasSelf;
- (BOOL) hasDest;
- (BOOL) hasContentType;
- (BOOL) hasContentTime;
- (BOOL) hasContent;
- (BOOL) hasFile;
- (BOOL) hasInitialFileName;
- (BOOL) hasNewFileName;
- (BOOL) hasChatType;
- (BOOL) hasGroupId;
@property (readonly, retain) NSString* self;
@property (readonly, retain) NSString* dest;
@property (readonly) ContentType contentType;
@property (readonly, retain) NSString* contentTime;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSData* file;
@property (readonly, retain) NSString* initialFileName;
@property (readonly, retain) NSString* newFileName;
@property (readonly) ChatType chatType;
@property (readonly, retain) NSString* groupId;

+ (CPrivateChat*) defaultInstance;
- (CPrivateChat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CPrivateChat_Builder*) builder;
+ (CPrivateChat_Builder*) builder;
+ (CPrivateChat_Builder*) builderWithPrototype:(CPrivateChat*) prototype;

+ (CPrivateChat*) parseFromData:(NSData*) data;
+ (CPrivateChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CPrivateChat*) parseFromInputStream:(NSInputStream*) input;
+ (CPrivateChat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (CPrivateChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CPrivateChat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CPrivateChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CPrivateChat_Builder : PBGeneratedMessage_Builder {
@private
  CPrivateChat* result;
}

- (CPrivateChat*) defaultInstance;

- (CPrivateChat_Builder*) clear;
- (CPrivateChat_Builder*) clone;

- (CPrivateChat*) build;
- (CPrivateChat*) buildPartial;

- (CPrivateChat_Builder*) mergeFrom:(CPrivateChat*) other;
- (CPrivateChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CPrivateChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSelf;
- (NSString*) self;
- (CPrivateChat_Builder*) setSelf:(NSString*) value;
- (CPrivateChat_Builder*) clearSelf;

- (BOOL) hasDest;
- (NSString*) dest;
- (CPrivateChat_Builder*) setDest:(NSString*) value;
- (CPrivateChat_Builder*) clearDest;

- (BOOL) hasContentType;
- (ContentType) contentType;
- (CPrivateChat_Builder*) setContentType:(ContentType) value;
- (CPrivateChat_Builder*) clearContentType;

- (BOOL) hasContentTime;
- (NSString*) contentTime;
- (CPrivateChat_Builder*) setContentTime:(NSString*) value;
- (CPrivateChat_Builder*) clearContentTime;

- (BOOL) hasContent;
- (NSString*) content;
- (CPrivateChat_Builder*) setContent:(NSString*) value;
- (CPrivateChat_Builder*) clearContent;

- (BOOL) hasFile;
- (NSData*) file;
- (CPrivateChat_Builder*) setFile:(NSData*) value;
- (CPrivateChat_Builder*) clearFile;

- (BOOL) hasInitialFileName;
- (NSString*) initialFileName;
- (CPrivateChat_Builder*) setInitialFileName:(NSString*) value;
- (CPrivateChat_Builder*) clearInitialFileName;

- (BOOL) hasNewFileName;
- (NSString*) newFileName;
- (CPrivateChat_Builder*) setNewFileName:(NSString*) value;
- (CPrivateChat_Builder*) clearNewFileName;

- (BOOL) hasChatType;
- (ChatType) chatType;
- (CPrivateChat_Builder*) setChatType:(ChatType) value;
- (CPrivateChat_Builder*) clearChatType;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (CPrivateChat_Builder*) setGroupId:(NSString*) value;
- (CPrivateChat_Builder*) clearGroupId;
@end

@interface CFileChat : PBGeneratedMessage {
@private
  BOOL hasInitialFileName_:1;
  BOOL hasNewFileName_:1;
  BOOL hasFile_:1;
  NSString* initialFileName;
  NSString* newFileName;
  NSData* file;
}
- (BOOL) hasFile;
- (BOOL) hasInitialFileName;
- (BOOL) hasNewFileName;
@property (readonly, retain) NSData* file;
@property (readonly, retain) NSString* initialFileName;
@property (readonly, retain) NSString* newFileName;

+ (CFileChat*) defaultInstance;
- (CFileChat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CFileChat_Builder*) builder;
+ (CFileChat_Builder*) builder;
+ (CFileChat_Builder*) builderWithPrototype:(CFileChat*) prototype;

+ (CFileChat*) parseFromData:(NSData*) data;
+ (CFileChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFileChat*) parseFromInputStream:(NSInputStream*) input;
+ (CFileChat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (CFileChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CFileChat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CFileChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CFileChat_Builder : PBGeneratedMessage_Builder {
@private
  CFileChat* result;
}

- (CFileChat*) defaultInstance;

- (CFileChat_Builder*) clear;
- (CFileChat_Builder*) clone;

- (CFileChat*) build;
- (CFileChat*) buildPartial;

- (CFileChat_Builder*) mergeFrom:(CFileChat*) other;
- (CFileChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CFileChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFile;
- (NSData*) file;
- (CFileChat_Builder*) setFile:(NSData*) value;
- (CFileChat_Builder*) clearFile;

- (BOOL) hasInitialFileName;
- (NSString*) initialFileName;
- (CFileChat_Builder*) setInitialFileName:(NSString*) value;
- (CFileChat_Builder*) clearInitialFileName;

- (BOOL) hasNewFileName;
- (NSString*) newFileName;
- (CFileChat_Builder*) setNewFileName:(NSString*) value;
- (CFileChat_Builder*) clearNewFileName;
@end

@interface CListChat : PBGeneratedMessage {
@private
  NSMutableArray* mutableChatsList;
}
- (NSArray*) chatsList;
- (CPrivateChat*) chatsAtIndex:(int32_t) index;

+ (CListChat*) defaultInstance;
- (CListChat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CListChat_Builder*) builder;
+ (CListChat_Builder*) builder;
+ (CListChat_Builder*) builderWithPrototype:(CListChat*) prototype;

+ (CListChat*) parseFromData:(NSData*) data;
+ (CListChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CListChat*) parseFromInputStream:(NSInputStream*) input;
+ (CListChat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (CListChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CListChat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CListChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CListChat_Builder : PBGeneratedMessage_Builder {
@private
  CListChat* result;
}

- (CListChat*) defaultInstance;

- (CListChat_Builder*) clear;
- (CListChat_Builder*) clone;

- (CListChat*) build;
- (CListChat*) buildPartial;

- (CListChat_Builder*) mergeFrom:(CListChat*) other;
- (CListChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CListChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) chatsList;
- (CPrivateChat*) chatsAtIndex:(int32_t) index;
- (CListChat_Builder*) replaceChatsAtIndex:(int32_t) index with:(CPrivateChat*) value;
- (CListChat_Builder*) addChats:(CPrivateChat*) value;
- (CListChat_Builder*) addAllChats:(NSArray*) values;
- (CListChat_Builder*) clearChatsList;
@end

@interface CLineChat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasLineState_:1;
  NSString* userId;
  StateType lineState;
}
- (BOOL) hasLineState;
- (BOOL) hasUserId;
@property (readonly) StateType lineState;
@property (readonly, retain) NSString* userId;

+ (CLineChat*) defaultInstance;
- (CLineChat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CLineChat_Builder*) builder;
+ (CLineChat_Builder*) builder;
+ (CLineChat_Builder*) builderWithPrototype:(CLineChat*) prototype;

+ (CLineChat*) parseFromData:(NSData*) data;
+ (CLineChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CLineChat*) parseFromInputStream:(NSInputStream*) input;
+ (CLineChat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (CLineChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CLineChat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CLineChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CLineChat_Builder : PBGeneratedMessage_Builder {
@private
  CLineChat* result;
}

- (CLineChat*) defaultInstance;

- (CLineChat_Builder*) clear;
- (CLineChat_Builder*) clone;

- (CLineChat*) build;
- (CLineChat*) buildPartial;

- (CLineChat_Builder*) mergeFrom:(CLineChat*) other;
- (CLineChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CLineChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLineState;
- (StateType) lineState;
- (CLineChat_Builder*) setLineState:(StateType) value;
- (CLineChat_Builder*) clearLineState;

- (BOOL) hasUserId;
- (NSString*) userId;
- (CLineChat_Builder*) setUserId:(NSString*) value;
- (CLineChat_Builder*) clearUserId;
@end

