// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class CLogin;
@class CLogin_Builder;
@class SResponse;
@class SResponse_Builder;
typedef enum {
  TypeWindows = 1,
  TypeAndroid = 2,
} Type;

BOOL TypeIsValidValue(Type value);


@interface LoginRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CLogin : PBGeneratedMessage {
@private
  BOOL hasUserid_:1;
  BOOL hasPasswd_:1;
  BOOL hasType_:1;
  NSString* userid;
  NSString* passwd;
  Type type;
}
- (BOOL) hasUserid;
- (BOOL) hasType;
- (BOOL) hasPasswd;
@property (readonly, retain) NSString* userid;
@property (readonly) Type type;
@property (readonly, retain) NSString* passwd;

+ (CLogin*) defaultInstance;
- (CLogin*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CLogin_Builder*) builder;
+ (CLogin_Builder*) builder;
+ (CLogin_Builder*) builderWithPrototype:(CLogin*) prototype;

+ (CLogin*) parseFromData:(NSData*) data;
+ (CLogin*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CLogin*) parseFromInputStream:(NSInputStream*) input;
+ (CLogin*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (CLogin*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CLogin*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CLogin*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CLogin_Builder : PBGeneratedMessage_Builder {
@private
  CLogin* result;
}

- (CLogin*) defaultInstance;

- (CLogin_Builder*) clear;
- (CLogin_Builder*) clone;

- (CLogin*) build;
- (CLogin*) buildPartial;

- (CLogin_Builder*) mergeFrom:(CLogin*) other;
- (CLogin_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CLogin_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserid;
- (NSString*) userid;
- (CLogin_Builder*) setUserid:(NSString*) value;
- (CLogin_Builder*) clearUserid;

- (BOOL) hasType;
- (Type) type;
- (CLogin_Builder*) setType:(Type) value;
- (CLogin_Builder*) clearType;

- (BOOL) hasPasswd;
- (NSString*) passwd;
- (CLogin_Builder*) setPasswd:(NSString*) value;
- (CLogin_Builder*) clearPasswd;
@end

@interface SResponse : PBGeneratedMessage {
@private
  BOOL hasCode_:1;
  BOOL hasDesc_:1;
  int32_t code;
  NSString* desc;
  NSMutableArray* mutableOnLineUsersList;
}
- (BOOL) hasCode;
- (BOOL) hasDesc;
@property (readonly) int32_t code;
@property (readonly, retain) NSString* desc;
- (NSArray*) onLineUsersList;
- (NSString*) onLineUsersAtIndex:(int32_t) index;

+ (SResponse*) defaultInstance;
- (SResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SResponse_Builder*) builder;
+ (SResponse_Builder*) builder;
+ (SResponse_Builder*) builderWithPrototype:(SResponse*) prototype;

+ (SResponse*) parseFromData:(NSData*) data;
+ (SResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SResponse*) parseFromInputStream:(NSInputStream*) input;
+ (SResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (SResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SResponse_Builder : PBGeneratedMessage_Builder {
@private
  SResponse* result;
}

- (SResponse*) defaultInstance;

- (SResponse_Builder*) clear;
- (SResponse_Builder*) clone;

- (SResponse*) build;
- (SResponse*) buildPartial;

- (SResponse_Builder*) mergeFrom:(SResponse*) other;
- (SResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (int32_t) code;
- (SResponse_Builder*) setCode:(int32_t) value;
- (SResponse_Builder*) clearCode;

- (NSArray*) onLineUsersList;
- (NSString*) onLineUsersAtIndex:(int32_t) index;
- (SResponse_Builder*) replaceOnLineUsersAtIndex:(int32_t) index with:(NSString*) value;
- (SResponse_Builder*) addOnLineUsers:(NSString*) value;
- (SResponse_Builder*) addAllOnLineUsers:(NSArray*) values;
- (SResponse_Builder*) clearOnLineUsersList;

- (BOOL) hasDesc;
- (NSString*) desc;
- (SResponse_Builder*) setDesc:(NSString*) value;
- (SResponse_Builder*) clearDesc;
@end

