# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socketTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for socketTest

pod 'CocoaAsyncSocket', '~> 7.6.1'
pod 'AsyncNetwork', '~> 1.1.1'
pod 'protobuf-ios', '~> 2.3.2'
  target 'socketTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'socketTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
