// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cli_def/login.proto

package protobuf.generate.cli2srv.login;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>windows = 1;</code>
     *
     * <pre>
     *电脑
     * </pre>
     */
    windows(0, 1),
    /**
     * <code>android = 2;</code>
     *
     * <pre>
     *手机
     * </pre>
     */
    android(1, 2),
    ;

    /**
     * <code>windows = 1;</code>
     *
     * <pre>
     *电脑
     * </pre>
     */
    public static final int windows_VALUE = 1;
    /**
     * <code>android = 2;</code>
     *
     * <pre>
     *手机
     * </pre>
     */
    public static final int android_VALUE = 2;


    public final int getNumber() { return value; }

    public static Type valueOf(int value) {
      switch (value) {
        case 1: return windows;
        case 2: return android;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.generate.cli2srv.login.Auth.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Type)
  }

  public interface CLoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string userid = 1;
    /**
     * <code>required string userid = 1;</code>
     *
     * <pre>
     * 用户账户id
     * </pre>
     */
    boolean hasUserid();
    /**
     * <code>required string userid = 1;</code>
     *
     * <pre>
     * 用户账户id
     * </pre>
     */
    java.lang.String getUserid();
    /**
     * <code>required string userid = 1;</code>
     *
     * <pre>
     * 用户账户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    // required .Type type = 2;
    /**
     * <code>required .Type type = 2;</code>
     *
     * <pre>
     *登录类型 默认为电脑
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .Type type = 2;</code>
     *
     * <pre>
     *登录类型 默认为电脑
     * </pre>
     */
    protobuf.generate.cli2srv.login.Auth.Type getType();

    // optional string passwd = 3;
    /**
     * <code>optional string passwd = 3;</code>
     *
     * <pre>
     * 用户密码
     * </pre>
     */
    boolean hasPasswd();
    /**
     * <code>optional string passwd = 3;</code>
     *
     * <pre>
     * 用户密码
     * </pre>
     */
    java.lang.String getPasswd();
    /**
     * <code>optional string passwd = 3;</code>
     *
     * <pre>
     * 用户密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();
  }
  /**
   * Protobuf type {@code CLogin}
   */
  public static final class CLogin extends
      com.google.protobuf.GeneratedMessage
      implements CLoginOrBuilder {
    // Use CLogin.newBuilder() to construct.
    private CLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CLogin defaultInstance;
    public static CLogin getDefaultInstance() {
      return defaultInstance;
    }

    public CLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userid_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              protobuf.generate.cli2srv.login.Auth.Type value = protobuf.generate.cli2srv.login.Auth.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              passwd_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.generate.cli2srv.login.Auth.internal_static_CLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.generate.cli2srv.login.Auth.internal_static_CLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.generate.cli2srv.login.Auth.CLogin.class, protobuf.generate.cli2srv.login.Auth.CLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<CLogin> PARSER =
        new com.google.protobuf.AbstractParser<CLogin>() {
      public CLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string userid = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userid_;
    /**
     * <code>required string userid = 1;</code>
     *
     * <pre>
     * 用户账户id
     * </pre>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userid = 1;</code>
     *
     * <pre>
     * 用户账户id
     * </pre>
     */
    public java.lang.String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userid = 1;</code>
     *
     * <pre>
     * 用户账户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .Type type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private protobuf.generate.cli2srv.login.Auth.Type type_;
    /**
     * <code>required .Type type = 2;</code>
     *
     * <pre>
     *登录类型 默认为电脑
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Type type = 2;</code>
     *
     * <pre>
     *登录类型 默认为电脑
     * </pre>
     */
    public protobuf.generate.cli2srv.login.Auth.Type getType() {
      return type_;
    }

    // optional string passwd = 3;
    public static final int PASSWD_FIELD_NUMBER = 3;
    private java.lang.Object passwd_;
    /**
     * <code>optional string passwd = 3;</code>
     *
     * <pre>
     * 用户密码
     * </pre>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string passwd = 3;</code>
     *
     * <pre>
     * 用户密码
     * </pre>
     */
    public java.lang.String getPasswd() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passwd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string passwd = 3;</code>
     *
     * <pre>
     * 用户密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      java.lang.Object ref = passwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userid_ = "";
      type_ = protobuf.generate.cli2srv.login.Auth.Type.windows;
      passwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUseridBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.generate.cli2srv.login.Auth.CLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.generate.cli2srv.login.Auth.CLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.generate.cli2srv.login.Auth.internal_static_CLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.generate.cli2srv.login.Auth.internal_static_CLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.generate.cli2srv.login.Auth.CLogin.class, protobuf.generate.cli2srv.login.Auth.CLogin.Builder.class);
      }

      // Construct using protobuf.generate.cli2srv.login.Auth.CLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = protobuf.generate.cli2srv.login.Auth.Type.windows;
        bitField0_ = (bitField0_ & ~0x00000002);
        passwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.generate.cli2srv.login.Auth.internal_static_CLogin_descriptor;
      }

      public protobuf.generate.cli2srv.login.Auth.CLogin getDefaultInstanceForType() {
        return protobuf.generate.cli2srv.login.Auth.CLogin.getDefaultInstance();
      }

      public protobuf.generate.cli2srv.login.Auth.CLogin build() {
        protobuf.generate.cli2srv.login.Auth.CLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.generate.cli2srv.login.Auth.CLogin buildPartial() {
        protobuf.generate.cli2srv.login.Auth.CLogin result = new protobuf.generate.cli2srv.login.Auth.CLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.passwd_ = passwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.generate.cli2srv.login.Auth.CLogin) {
          return mergeFrom((protobuf.generate.cli2srv.login.Auth.CLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.generate.cli2srv.login.Auth.CLogin other) {
        if (other == protobuf.generate.cli2srv.login.Auth.CLogin.getDefaultInstance()) return this;
        if (other.hasUserid()) {
          bitField0_ |= 0x00000001;
          userid_ = other.userid_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPasswd()) {
          bitField0_ |= 0x00000004;
          passwd_ = other.passwd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserid()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.generate.cli2srv.login.Auth.CLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.generate.cli2srv.login.Auth.CLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string userid = 1;
      private java.lang.Object userid_ = "";
      /**
       * <code>required string userid = 1;</code>
       *
       * <pre>
       * 用户账户id
       * </pre>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string userid = 1;</code>
       *
       * <pre>
       * 用户账户id
       * </pre>
       */
      public java.lang.String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userid = 1;</code>
       *
       * <pre>
       * 用户账户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        java.lang.Object ref = userid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userid = 1;</code>
       *
       * <pre>
       * 用户账户id
       * </pre>
       */
      public Builder setUserid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userid = 1;</code>
       *
       * <pre>
       * 用户账户id
       * </pre>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      /**
       * <code>required string userid = 1;</code>
       *
       * <pre>
       * 用户账户id
       * </pre>
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userid_ = value;
        onChanged();
        return this;
      }

      // required .Type type = 2;
      private protobuf.generate.cli2srv.login.Auth.Type type_ = protobuf.generate.cli2srv.login.Auth.Type.windows;
      /**
       * <code>required .Type type = 2;</code>
       *
       * <pre>
       *登录类型 默认为电脑
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Type type = 2;</code>
       *
       * <pre>
       *登录类型 默认为电脑
       * </pre>
       */
      public protobuf.generate.cli2srv.login.Auth.Type getType() {
        return type_;
      }
      /**
       * <code>required .Type type = 2;</code>
       *
       * <pre>
       *登录类型 默认为电脑
       * </pre>
       */
      public Builder setType(protobuf.generate.cli2srv.login.Auth.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Type type = 2;</code>
       *
       * <pre>
       *登录类型 默认为电脑
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = protobuf.generate.cli2srv.login.Auth.Type.windows;
        onChanged();
        return this;
      }

      // optional string passwd = 3;
      private java.lang.Object passwd_ = "";
      /**
       * <code>optional string passwd = 3;</code>
       *
       * <pre>
       * 用户密码
       * </pre>
       */
      public boolean hasPasswd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string passwd = 3;</code>
       *
       * <pre>
       * 用户密码
       * </pre>
       */
      public java.lang.String getPasswd() {
        java.lang.Object ref = passwd_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          passwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string passwd = 3;</code>
       *
       * <pre>
       * 用户密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        java.lang.Object ref = passwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string passwd = 3;</code>
       *
       * <pre>
       * 用户密码
       * </pre>
       */
      public Builder setPasswd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passwd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 3;</code>
       *
       * <pre>
       * 用户密码
       * </pre>
       */
      public Builder clearPasswd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passwd_ = getDefaultInstance().getPasswd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string passwd = 3;</code>
       *
       * <pre>
       * 用户密码
       * </pre>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passwd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CLogin)
    }

    static {
      defaultInstance = new CLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CLogin)
  }

  public interface SResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *返回码
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *返回码
     * </pre>
     */
    int getCode();

    // repeated string onLineUsers = 2;
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    java.util.List<java.lang.String>
    getOnLineUsersList();
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    int getOnLineUsersCount();
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    java.lang.String getOnLineUsers(int index);
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    com.google.protobuf.ByteString
        getOnLineUsersBytes(int index);

    // required string desc = 3;
    /**
     * <code>required string desc = 3;</code>
     *
     * <pre>
     *描述
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 3;</code>
     *
     * <pre>
     *描述
     * </pre>
     */
    java.lang.String getDesc();
    /**
     * <code>required string desc = 3;</code>
     *
     * <pre>
     *描述
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * Protobuf type {@code SResponse}
   *
   * <pre>
   *
   *code：
   *200 -- ok
   *404 -- error
   *300 -- dumplicated registery
   * </pre>
   */
  public static final class SResponse extends
      com.google.protobuf.GeneratedMessage
      implements SResponseOrBuilder {
    // Use SResponse.newBuilder() to construct.
    private SResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SResponse defaultInstance;
    public static SResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                onLineUsers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              onLineUsers_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              desc_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          onLineUsers_ = new com.google.protobuf.UnmodifiableLazyStringList(onLineUsers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.generate.cli2srv.login.Auth.internal_static_SResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.generate.cli2srv.login.Auth.internal_static_SResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.generate.cli2srv.login.Auth.SResponse.class, protobuf.generate.cli2srv.login.Auth.SResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SResponse> PARSER =
        new com.google.protobuf.AbstractParser<SResponse>() {
      public SResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *返回码
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *返回码
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    // repeated string onLineUsers = 2;
    public static final int ONLINEUSERS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList onLineUsers_;
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    public java.util.List<java.lang.String>
        getOnLineUsersList() {
      return onLineUsers_;
    }
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    public int getOnLineUsersCount() {
      return onLineUsers_.size();
    }
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    public java.lang.String getOnLineUsers(int index) {
      return onLineUsers_.get(index);
    }
    /**
     * <code>repeated string onLineUsers = 2;</code>
     *
     * <pre>
     *上线人数用户编号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOnLineUsersBytes(int index) {
      return onLineUsers_.getByteString(index);
    }

    // required string desc = 3;
    public static final int DESC_FIELD_NUMBER = 3;
    private java.lang.Object desc_;
    /**
     * <code>required string desc = 3;</code>
     *
     * <pre>
     *描述
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string desc = 3;</code>
     *
     * <pre>
     *描述
     * </pre>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 3;</code>
     *
     * <pre>
     *描述
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = 0;
      onLineUsers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      desc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      for (int i = 0; i < onLineUsers_.size(); i++) {
        output.writeBytes(2, onLineUsers_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getDescBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < onLineUsers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(onLineUsers_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getOnLineUsersList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.generate.cli2srv.login.Auth.SResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SResponse}
     *
     * <pre>
     *
     *code：
     *200 -- ok
     *404 -- error
     *300 -- dumplicated registery
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.generate.cli2srv.login.Auth.SResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.generate.cli2srv.login.Auth.internal_static_SResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.generate.cli2srv.login.Auth.internal_static_SResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.generate.cli2srv.login.Auth.SResponse.class, protobuf.generate.cli2srv.login.Auth.SResponse.Builder.class);
      }

      // Construct using protobuf.generate.cli2srv.login.Auth.SResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        onLineUsers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.generate.cli2srv.login.Auth.internal_static_SResponse_descriptor;
      }

      public protobuf.generate.cli2srv.login.Auth.SResponse getDefaultInstanceForType() {
        return protobuf.generate.cli2srv.login.Auth.SResponse.getDefaultInstance();
      }

      public protobuf.generate.cli2srv.login.Auth.SResponse build() {
        protobuf.generate.cli2srv.login.Auth.SResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.generate.cli2srv.login.Auth.SResponse buildPartial() {
        protobuf.generate.cli2srv.login.Auth.SResponse result = new protobuf.generate.cli2srv.login.Auth.SResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          onLineUsers_ = new com.google.protobuf.UnmodifiableLazyStringList(
              onLineUsers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.onLineUsers_ = onLineUsers_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desc_ = desc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.generate.cli2srv.login.Auth.SResponse) {
          return mergeFrom((protobuf.generate.cli2srv.login.Auth.SResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.generate.cli2srv.login.Auth.SResponse other) {
        if (other == protobuf.generate.cli2srv.login.Auth.SResponse.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.onLineUsers_.isEmpty()) {
          if (onLineUsers_.isEmpty()) {
            onLineUsers_ = other.onLineUsers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureOnLineUsersIsMutable();
            onLineUsers_.addAll(other.onLineUsers_);
          }
          onChanged();
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000004;
          desc_ = other.desc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (!hasDesc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.generate.cli2srv.login.Auth.SResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.generate.cli2srv.login.Auth.SResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *返回码
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *返回码
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *返回码
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *返回码
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // repeated string onLineUsers = 2;
      private com.google.protobuf.LazyStringList onLineUsers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOnLineUsersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          onLineUsers_ = new com.google.protobuf.LazyStringArrayList(onLineUsers_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public java.util.List<java.lang.String>
          getOnLineUsersList() {
        return java.util.Collections.unmodifiableList(onLineUsers_);
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public int getOnLineUsersCount() {
        return onLineUsers_.size();
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public java.lang.String getOnLineUsers(int index) {
        return onLineUsers_.get(index);
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOnLineUsersBytes(int index) {
        return onLineUsers_.getByteString(index);
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public Builder setOnLineUsers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOnLineUsersIsMutable();
        onLineUsers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public Builder addOnLineUsers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOnLineUsersIsMutable();
        onLineUsers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public Builder addAllOnLineUsers(
          java.lang.Iterable<java.lang.String> values) {
        ensureOnLineUsersIsMutable();
        super.addAll(values, onLineUsers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public Builder clearOnLineUsers() {
        onLineUsers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string onLineUsers = 2;</code>
       *
       * <pre>
       *上线人数用户编号
       * </pre>
       */
      public Builder addOnLineUsersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOnLineUsersIsMutable();
        onLineUsers_.add(value);
        onChanged();
        return this;
      }

      // required string desc = 3;
      private java.lang.Object desc_ = "";
      /**
       * <code>required string desc = 3;</code>
       *
       * <pre>
       *描述
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string desc = 3;</code>
       *
       * <pre>
       *描述
       * </pre>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string desc = 3;</code>
       *
       * <pre>
       *描述
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 3;</code>
       *
       * <pre>
       *描述
       * </pre>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 3;</code>
       *
       * <pre>
       *描述
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 3;</code>
       *
       * <pre>
       *描述
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SResponse)
    }

    static {
      defaultInstance = new SResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CLogin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023cli_def/login.proto\"=\n\006CLogin\022\016\n\006useri" +
      "d\030\001 \002(\t\022\023\n\004type\030\002 \002(\0162\005.Type\022\016\n\006passwd\030\003" +
      " \001(\t\"<\n\tSResponse\022\014\n\004code\030\001 \002(\005\022\023\n\013onLin" +
      "eUsers\030\002 \003(\t\022\014\n\004desc\030\003 \002(\t* \n\004Type\022\013\n\007wi" +
      "ndows\020\001\022\013\n\007android\020\002B\'\n\037protobuf.generat" +
      "e.cli2srv.loginB\004Auth"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CLogin_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CLogin_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CLogin_descriptor,
              new java.lang.String[] { "Userid", "Type", "Passwd", });
          internal_static_SResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SResponse_descriptor,
              new java.lang.String[] { "Code", "OnLineUsers", "Desc", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
